syntax = "proto3";
package DeviceCapabilities;

message DeviceCapabilities {
     ChatLockSupportLevel chatLockSupportLevel = 1;
     LIDMigration lidMigration = 2;
     BusinessBroadcast businessBroadcast = 3;
     UserHasAvatar userHasAvatar = 4;
     MemberNameTagPrimarySupport memberNameTagPrimarySupport = 5;
     AiThread aiThread = 6;
    message AiThread {
         SupportLevel supportLevel = 1;
        enum SupportLevel {
            NONE = 0;
            INFRA = 1;
            FULL = 2;
        }
    }
    message BusinessBroadcast {
         bool importListEnabled = 1;
    }
    enum ChatLockSupportLevel {
        NONE = 0;
        MINIMAL = 1;
        FULL = 2;
    }
    message LIDMigration {
         uint64 chatDbMigrationTimestamp = 1;
    }
    enum MemberNameTagPrimarySupport {
        DISABLED = 0;
        RECEIVER_ENABLED = 1;
        SENDER_ENABLED = 2;
    }
    message UserHasAvatar {
         bool userHasAvatar = 1;
    }
}