syntax = "proto3";
package E2E;

import "../Protocol/Protocol.proto";
import "../AICommon/AICommon.proto";
import "../Adv/Adv.proto";
import "../StatusAttributions/StatusAttributions.proto";
import "../CompanionReg/CompanionReg.proto";
import "../MmsRetry/MmsRetry.proto";

message AIQueryFanout {
     Protocol.MessageKey messageKey = 1;
     Message message = 2;
     int64 timestamp = 3;
}

message AIRichResponseMessage {
     AICommon.AIRichResponseMessageType messageType = 1;
    repeated AICommon.AIRichResponseSubMessage submessages = 2;
     AICommon.AIRichResponseUnifiedResponse unifiedResponse = 3;
     ContextInfo contextInfo = 4;
}

message MemberLabel {
     string label = 1;
     int64 labelTimestamp = 2;
}

message UrlTrackingMap {
    repeated UrlTrackingMapElement urlTrackingMapElements = 1;
    message UrlTrackingMapElement {
         string originalUrl = 1;
         string unconsentedUsersUrl = 2;
         string consentedUsersUrl = 3;
         uint32 cardIndex = 4;
    }
}

message ProcessedVideo {
     string directPath = 1;
     bytes fileSha256 = 2;
     uint32 height = 3;
     uint32 width = 4;
     uint64 fileLength = 5;
     uint32 bitrate = 6;
     VideoQuality quality = 7;
    repeated string capabilities = 8;
    enum VideoQuality {
        UNDEFINED = 0;
        LOW = 1;
        MID = 2;
        HIGH = 3;
    }
}

message LIDMigrationMappingSyncMessage {
     bytes encodedMappingPayload = 1;
}

message MediaNotifyMessage {
     string expressPathUrl = 1;
     bytes fileEncSha256 = 2;
     uint64 fileLength = 3;
}

message MessageSecretMessage {
     sfixed32 version = 1;
     bytes encIv = 2;
     bytes encPayload = 3;
}

message GroupMention {
     string groupJid = 1;
     string groupSubject = 2;
}

message ActionLink {
     string url = 1;
     string buttonTitle = 2;
}

message DisappearingMode {
     Initiator initiator = 1;
     Trigger trigger = 2;
     string initiatorDeviceJid = 3;
     bool initiatedByMe = 4;
    enum Initiator {
        CHANGED_IN_CHAT = 0;
        INITIATED_BY_ME = 1;
        INITIATED_BY_OTHER = 2;
        BIZ_UPGRADE_FB_HOSTING = 3;
    }
    enum Trigger {
        UNKNOWN = 0;
        CHAT_SETTING = 1;
        ACCOUNT_SETTING = 2;
        BULK_CHANGE = 3;
        BIZ_SUPPORTS_FB_HOSTING = 4;
        UNKNOWN_GROUPS = 5;
    }
}

message PaymentBackground {
     string id = 1;
     uint64 fileLength = 2;
     uint32 width = 3;
     uint32 height = 4;
     string mimetype = 5;
     fixed32 placeholderArgb = 6;
     fixed32 textArgb = 7;
     fixed32 subtextArgb = 8;
     MediaData mediaData = 9;
     Type type = 10;
    message MediaData {
         bytes mediaKey = 1;
         int64 mediaKeyTimestamp = 2;
         bytes fileSha256 = 3;
         bytes fileEncSha256 = 4;
         string directPath = 5;
    }
    enum Type {
        UNKNOWN = 0;
        DEFAULT = 1;
    }
}

message Money {
     int64 value = 1;
     uint32 offset = 2;
     string currencyCode = 3;
}

message HydratedTemplateButton {
     uint32 index = 4;
    oneof hydratedButton {
        HydratedTemplateButton.HydratedQuickReplyButton quickReplyButton = 1;
        HydratedTemplateButton.HydratedURLButton urlButton = 2;
        HydratedTemplateButton.HydratedCallButton callButton = 3;
    }
    message HydratedCallButton {
         string displayText = 1;
         string phoneNumber = 2;
    }
    message HydratedQuickReplyButton {
         string displayText = 1;
         string id = 2;
    }
    message HydratedURLButton {
         string displayText = 1;
         string url = 2;
         string consentedUsersUrl = 3;
         WebviewPresentationType webviewPresentation = 4;
        enum WebviewPresentationType {
            FULL = 1;
            TALL = 2;
            COMPACT = 3;
        }
    }
}

message TemplateButton {
     uint32 index = 4;
    oneof button {
        TemplateButton.QuickReplyButton quickReplyButton = 1;
        TemplateButton.URLButton urlButton = 2;
        TemplateButton.CallButton callButton = 3;
    }
    message CallButton {
         Message.HighlyStructuredMessage displayText = 1;
         Message.HighlyStructuredMessage phoneNumber = 2;
    }
    message QuickReplyButton {
         Message.HighlyStructuredMessage displayText = 1;
         string id = 2;
    }
    message URLButton {
         Message.HighlyStructuredMessage displayText = 1;
         Message.HighlyStructuredMessage url = 2;
    }
}

message Location {
     double degreesLatitude = 1;
     double degreesLongitude = 2;
     string name = 3;
}

message Point {
     int32 xDeprecated = 1;
     int32 yDeprecated = 2;
     double x = 3;
     double y = 4;
}

message InteractiveAnnotation {
    repeated Point polygonVertices = 1;
     bool shouldSkipConfirmation = 4;
     EmbeddedContent embeddedContent = 5;
     StatusLinkType statusLinkType = 8;
    oneof action {
        Location location = 2;
        ContextInfo.ForwardedNewsletterMessageInfo newsletter = 3;
        bool embeddedAction = 6;
        TapLinkAction tapAction = 7;
    }
    enum StatusLinkType {
        RASTERIZED_LINK_PREVIEW = 1;
        RASTERIZED_LINK_TRUNCATED = 2;
        RASTERIZED_LINK_FULL_URL = 3;
    }
}

message TapLinkAction {
     string title = 1;
     string tapUrl = 2;
}

message EmbeddedContent {
    oneof content {
        EmbeddedMessage embeddedMessage = 1;
        EmbeddedMusic embeddedMusic = 2;
    }
}

message EmbeddedMusic {
     string musicContentMediaId = 1;
     string songId = 2;
     string author = 3;
     string title = 4;
     string artworkDirectPath = 5;
     bytes artworkSha256 = 6;
     bytes artworkEncSha256 = 7;
     string artistAttribution = 8;
     bytes countryBlocklist = 9;
     bool isExplicit = 10;
     bytes artworkMediaKey = 11;
     int64 musicSongStartTimeInMs = 12;
     int64 derivedContentStartTimeInMs = 13;
     int64 overlapDurationInMs = 14;
}

message EmbeddedMessage {
     string stanzaId = 1;
     Message message = 2;
}

message DeviceListMetadata {
     bytes senderKeyHash = 1;
     uint64 senderTimestamp = 2;
    repeated uint32 senderKeyIndexes = 3 [packed=true];
     Adv.ADVEncryptionType senderAccountType = 4;
     Adv.ADVEncryptionType receiverAccountType = 5;
     bytes recipientKeyHash = 8;
     uint64 recipientTimestamp = 9;
    repeated uint32 recipientKeyIndexes = 10 [packed=true];
}

message MessageContextInfo {
     DeviceListMetadata deviceListMetadata = 1;
     int32 deviceListMetadataVersion = 2;
     bytes messageSecret = 3;
     bytes paddingBytes = 4;
     uint32 messageAddOnDurationInSecs = 5;
     bytes botMessageSecret = 6;
     AICommon.BotMetadata botMetadata = 7;
     int32 reportingTokenVersion = 8;
     MessageAddonExpiryType messageAddOnExpiryType = 9;
     MessageAssociation messageAssociation = 10;
     bool capiCreatedGroup = 11;
     string supportPayload = 12;
     Protocol.LimitSharing limitSharing = 13;
     Protocol.LimitSharing limitSharingV2 = 14;
    repeated ThreadID threadId = 15;
     WebLinkRenderConfig weblinkRenderConfig = 16;
    enum MessageAddonExpiryType {
        STATIC = 1;
        DEPENDENT_ON_PARENT = 2;
    }
}

message ThreadID {
     ThreadType threadType = 1;
     Protocol.MessageKey threadKey = 2;
    enum ThreadType {
        UNKNOWN = 0;
        VIEW_REPLIES = 1;
        AI_THREAD = 2;
    }
}

message MessageAssociation {
     AssociationType associationType = 1;
     Protocol.MessageKey parentMessageKey = 2;
     int32 messageIndex = 3;
    enum AssociationType {
        UNKNOWN = 0;
        MEDIA_ALBUM = 1;
        BOT_PLUGIN = 2;
        EVENT_COVER_IMAGE = 3;
        STATUS_POLL = 4;
        HD_VIDEO_DUAL_UPLOAD = 5;
        STATUS_EXTERNAL_RESHARE = 6;
        MEDIA_POLL = 7;
        STATUS_ADD_YOURS = 8;
        STATUS_NOTIFICATION = 9;
        HD_IMAGE_DUAL_UPLOAD = 10;
        STICKER_ANNOTATION = 11;
        MOTION_PHOTO = 12;
        STATUS_LINK_ACTION = 13;
        VIEW_ALL_REPLIES = 14;
        STATUS_ADD_YOURS_AI_IMAGINE = 15;
        STATUS_QUESTION = 16;
        STATUS_ADD_YOURS_DIWALI = 17;
        STATUS_REACTION = 18;
        HEVC_VIDEO_DUAL_UPLOAD = 19;
    }
}

message ContextInfo {
     string stanzaId = 1;
     string participant = 2;
     Message quotedMessage = 3;
     string remoteJid = 4;
    repeated string mentionedJid = 15;
     string conversionSource = 18;
     bytes conversionData = 19;
     uint32 conversionDelaySeconds = 20;
     uint32 forwardingScore = 21;
     bool isForwarded = 22;
     AdReplyInfo quotedAd = 23;
     Protocol.MessageKey placeholderKey = 24;
     uint32 expiration = 25;
     int64 ephemeralSettingTimestamp = 26;
     bytes ephemeralSharedSecret = 27;
     ExternalAdReplyInfo externalAdReply = 28;
     string entryPointConversionSource = 29;
     string entryPointConversionApp = 30;
     uint32 entryPointConversionDelaySeconds = 31;
     DisappearingMode disappearingMode = 32;
     ActionLink actionLink = 33;
     string groupSubject = 34;
     string parentGroupJid = 35;
     string trustBannerType = 37;
     uint32 trustBannerAction = 38;
     bool isSampled = 39;
    repeated GroupMention groupMentions = 40;
     UTMInfo utm = 41;
     ForwardedNewsletterMessageInfo forwardedNewsletterMessageInfo = 43;
     BusinessMessageForwardInfo businessMessageForwardInfo = 44;
     string smbClientCampaignId = 45;
     string smbServerCampaignId = 46;
     DataSharingContext dataSharingContext = 47;
     bool alwaysShowAdAttribution = 48;
     FeatureEligibilities featureEligibilities = 49;
     string entryPointConversionExternalSource = 50;
     string entryPointConversionExternalMedium = 51;
     string ctwaSignals = 54;
     bytes ctwaPayload = 55;
     AICommon.ForwardedAIBotMessageInfo forwardedAiBotMessageInfo = 56;
     StatusAttributionType statusAttributionType = 57;
     UrlTrackingMap urlTrackingMap = 58;
     PairedMediaType pairedMediaType = 59;
     uint32 rankingVersion = 60;
     MemberLabel memberLabel = 62;
     bool isQuestion = 63;
     StatusSourceType statusSourceType = 64;
    repeated StatusAttributions.StatusAttribution statusAttributions = 65;
     bool isGroupStatus = 66;
     ForwardOrigin forwardOrigin = 67;
     QuestionReplyQuotedMessage questionReplyQuotedMessage = 68;
     StatusAudienceMetadata statusAudienceMetadata = 69;
     uint32 nonJidMentions = 70;
     QuotedType quotedType = 71;
     AICommon.BotMessageSharingInfo botMessageSharingInfo = 72;
    message AdReplyInfo {
         string advertiserName = 1;
         MediaType mediaType = 2;
         bytes jpegThumbnail = 16;
         string caption = 17;
        enum MediaType {
            NONE = 0;
            IMAGE = 1;
            VIDEO = 2;
        }
    }
    message BusinessMessageForwardInfo {
         string businessOwnerJid = 1;
    }
    message DataSharingContext {
         bool showMmDisclosure = 1;
         string encryptedSignalTokenConsented = 2;
        repeated Parameters parameters = 3;
         int32 dataSharingFlags = 4;
        enum DataSharingFlags {
            SHOW_MM_DISCLOSURE_ON_CLICK = 1;
            SHOW_MM_DISCLOSURE_ON_READ = 2;
        }
        message Parameters {
             string key = 1;
             string stringData = 2;
             int64 intData = 3;
             float floatData = 4;
             ContextInfo.DataSharingContext.Parameters contents = 5;
        }
    }
    message ExternalAdReplyInfo {
         string title = 1;
         string body = 2;
         MediaType mediaType = 3;
         string thumbnailUrl = 4;
         string mediaUrl = 5;
         bytes thumbnail = 6;
         string sourceType = 7;
         string sourceId = 8;
         string sourceUrl = 9;
         bool containsAutoReply = 10;
         bool renderLargerThumbnail = 11;
         bool showAdAttribution = 12;
         string ctwaClid = 13;
         string ref = 14;
         bool clickToWhatsappCall = 15;
         bool adContextPreviewDismissed = 16;
         string sourceApp = 17;
         bool automatedGreetingMessageShown = 18;
         string greetingMessageBody = 19;
         string ctaPayload = 20;
         bool disableNudge = 21;
         string originalImageUrl = 22;
         string automatedGreetingMessageCtaType = 23;
         bool wtwaAdFormat = 24;
         AdType adType = 25;
         string wtwaWebsiteUrl = 26;
         string adPreviewUrl = 27;
        enum AdType {
            CTWA = 0;
            CAWC = 1;
        }
        enum MediaType {
            NONE = 0;
            IMAGE = 1;
            VIDEO = 2;
        }
    }
    message FeatureEligibilities {
         bool cannotBeReactedTo = 1;
         bool cannotBeRanked = 2;
         bool canRequestFeedback = 3;
         bool canBeReshared = 4;
         bool canReceiveMultiReact = 5;
    }
    enum ForwardOrigin {
        UNKNOWN = 0;
        CHAT = 1;
        STATUS = 2;
        CHANNELS = 3;
        META_AI = 4;
        UGC = 5;
    }
    message ForwardedNewsletterMessageInfo {
         string newsletterJid = 1;
         int32 serverMessageId = 2;
         string newsletterName = 3;
         ContentType contentType = 4;
         string accessibilityText = 5;
        enum ContentType {
            UPDATE = 1;
            UPDATE_CARD = 2;
            LINK_CARD = 3;
        }
    }
    enum PairedMediaType {
        NOT_PAIRED_MEDIA = 0;
        SD_VIDEO_PARENT = 1;
        HD_VIDEO_CHILD = 2;
        SD_IMAGE_PARENT = 3;
        HD_IMAGE_CHILD = 4;
        MOTION_PHOTO_PARENT = 5;
        MOTION_PHOTO_CHILD = 6;
        HEVC_VIDEO_PARENT = 7;
        HEVC_VIDEO_CHILD = 8;
    }
    message QuestionReplyQuotedMessage {
         int32 serverQuestionId = 1;
         Message quotedQuestion = 2;
         Message quotedResponse = 3;
    }
    enum QuotedType {
        EXPLICIT = 0;
        AUTO = 1;
    }
    enum StatusAttributionType {
        NONE = 0;
        RESHARED_FROM_MENTION = 1;
        RESHARED_FROM_POST = 2;
        RESHARED_FROM_POST_MANY_TIMES = 3;
        FORWARDED_FROM_STATUS = 4;
    }
    message StatusAudienceMetadata {
         AudienceType audienceType = 1;
        enum AudienceType {
            UNKNOWN = 0;
            CLOSE_FRIENDS = 1;
        }
    }
    enum StatusSourceType {
        IMAGE = 0;
        VIDEO = 1;
        GIF = 2;
        AUDIO = 3;
        TEXT = 4;
        MUSIC_STANDALONE = 5;
    }
    message UTMInfo {
         string utmSource = 1;
         string utmCampaign = 2;
    }
}

message Message {
     string conversation = 1;
     SenderKeyDistributionMessage senderKeyDistributionMessage = 2;
     ImageMessage imageMessage = 3;
     ContactMessage contactMessage = 4;
     LocationMessage locationMessage = 5;
     ExtendedTextMessage extendedTextMessage = 6;
     DocumentMessage documentMessage = 7;
     AudioMessage audioMessage = 8;
     VideoMessage videoMessage = 9;
     Call call = 10;
     Chat chat = 11;
     ProtocolMessage protocolMessage = 12;
     ContactsArrayMessage contactsArrayMessage = 13;
     HighlyStructuredMessage highlyStructuredMessage = 14;
     SenderKeyDistributionMessage fastRatchetKeySenderKeyDistributionMessage = 15;
     SendPaymentMessage sendPaymentMessage = 16;
     LiveLocationMessage liveLocationMessage = 18;
     RequestPaymentMessage requestPaymentMessage = 22;
     DeclinePaymentRequestMessage declinePaymentRequestMessage = 23;
     CancelPaymentRequestMessage cancelPaymentRequestMessage = 24;
     TemplateMessage templateMessage = 25;
     StickerMessage stickerMessage = 26;
     GroupInviteMessage groupInviteMessage = 28;
     TemplateButtonReplyMessage templateButtonReplyMessage = 29;
     ProductMessage productMessage = 30;
     DeviceSentMessage deviceSentMessage = 31;
     MessageContextInfo messageContextInfo = 35;
     ListMessage listMessage = 36;
     FutureProofMessage viewOnceMessage = 37;
     OrderMessage orderMessage = 38;
     ListResponseMessage listResponseMessage = 39;
     FutureProofMessage ephemeralMessage = 40;
     InvoiceMessage invoiceMessage = 41;
     ButtonsMessage buttonsMessage = 42;
     ButtonsResponseMessage buttonsResponseMessage = 43;
     PaymentInviteMessage paymentInviteMessage = 44;
     InteractiveMessage interactiveMessage = 45;
     ReactionMessage reactionMessage = 46;
     StickerSyncRMRMessage stickerSyncRmrMessage = 47;
     InteractiveResponseMessage interactiveResponseMessage = 48;
     PollCreationMessage pollCreationMessage = 49;
     PollUpdateMessage pollUpdateMessage = 50;
     KeepInChatMessage keepInChatMessage = 51;
     FutureProofMessage documentWithCaptionMessage = 53;
     RequestPhoneNumberMessage requestPhoneNumberMessage = 54;
     FutureProofMessage viewOnceMessageV2 = 55;
     EncReactionMessage encReactionMessage = 56;
     FutureProofMessage editedMessage = 58;
     FutureProofMessage viewOnceMessageV2Extension = 59;
     PollCreationMessage pollCreationMessageV2 = 60;
     ScheduledCallCreationMessage scheduledCallCreationMessage = 61;
     FutureProofMessage groupMentionedMessage = 62;
     PinInChatMessage pinInChatMessage = 63;
     PollCreationMessage pollCreationMessageV3 = 64;
     ScheduledCallEditMessage scheduledCallEditMessage = 65;
     VideoMessage ptvMessage = 66;
     FutureProofMessage botInvokeMessage = 67;
     CallLogMessage callLogMesssage = 69;
     MessageHistoryBundle messageHistoryBundle = 70;
     EncCommentMessage encCommentMessage = 71;
     BCallMessage bcallMessage = 72;
     FutureProofMessage lottieStickerMessage = 74;
     EventMessage eventMessage = 75;
     EncEventResponseMessage encEventResponseMessage = 76;
     CommentMessage commentMessage = 77;
     NewsletterAdminInviteMessage newsletterAdminInviteMessage = 78;
     PlaceholderMessage placeholderMessage = 80;
     SecretEncryptedMessage secretEncryptedMessage = 82;
     AlbumMessage albumMessage = 83;
     FutureProofMessage eventCoverImage = 85;
     StickerPackMessage stickerPackMessage = 86;
     FutureProofMessage statusMentionMessage = 87;
     PollResultSnapshotMessage pollResultSnapshotMessage = 88;
     FutureProofMessage pollCreationOptionImageMessage = 90;
     FutureProofMessage associatedChildMessage = 91;
     FutureProofMessage groupStatusMentionMessage = 92;
     FutureProofMessage pollCreationMessageV4 = 93;
     FutureProofMessage statusAddYours = 95;
     FutureProofMessage groupStatusMessage = 96;
     AIRichResponseMessage richResponseMessage = 97;
     StatusNotificationMessage statusNotificationMessage = 98;
     FutureProofMessage limitSharingMessage = 99;
     FutureProofMessage botTaskMessage = 100;
     FutureProofMessage questionMessage = 101;
     MessageHistoryNotice messageHistoryNotice = 102;
     FutureProofMessage groupStatusMessageV2 = 103;
     FutureProofMessage botForwardedMessage = 104;
     StatusQuestionAnswerMessage statusQuestionAnswerMessage = 105;
     FutureProofMessage questionReplyMessage = 106;
     QuestionResponseMessage questionResponseMessage = 107;
     StatusQuotedMessage statusQuotedMessage = 109;
     StatusStickerInteractionMessage statusStickerInteractionMessage = 110;
     PollCreationMessage pollCreationMessageV5 = 111;
     NewsletterFollowerInviteMessage newsletterFollowerInviteMessageV2 = 113;
     PollResultSnapshotMessage pollResultSnapshotMessageV3 = 115;
    message AlbumMessage {
         uint32 expectedImageCount = 2;
         uint32 expectedVideoCount = 3;
         ContextInfo contextInfo = 17;
    }
    message AppStateFatalExceptionNotification {
        repeated string collectionNames = 1;
         int64 timestamp = 2;
    }
    message AppStateSyncKey {
         Message.AppStateSyncKeyId keyId = 1;
         Message.AppStateSyncKeyData keyData = 2;
    }
    message AppStateSyncKeyData {
         bytes keyData = 1;
         Message.AppStateSyncKeyFingerprint fingerprint = 2;
         int64 timestamp = 3;
    }
    message AppStateSyncKeyFingerprint {
         uint32 rawId = 1;
         uint32 currentIndex = 2;
        repeated uint32 deviceIndexes = 3 [packed=true];
    }
    message AppStateSyncKeyId {
         bytes keyId = 1;
    }
    message AppStateSyncKeyRequest {
        repeated Message.AppStateSyncKeyId keyIds = 1;
    }
    message AppStateSyncKeyShare {
        repeated Message.AppStateSyncKey keys = 1;
    }
    message AudioMessage {
         string url = 1;
         string mimetype = 2;
         bytes fileSha256 = 3;
         uint64 fileLength = 4;
         uint32 seconds = 5;
         bool ptt = 6;
         bytes mediaKey = 7;
         bytes fileEncSha256 = 8;
         string directPath = 9;
         int64 mediaKeyTimestamp = 10;
         ContextInfo contextInfo = 17;
         bytes streamingSidecar = 18;
         bytes waveform = 19;
         fixed32 backgroundArgb = 20;
         bool viewOnce = 21;
         string accessibilityLabel = 22;
         Message.MediaKeyDomain mediaKeyDomain = 23;
    }
    message BCallMessage {
         string sessionId = 1;
         MediaType mediaType = 2;
         bytes masterKey = 3;
         string caption = 4;
        enum MediaType {
            UNKNOWN = 0;
            AUDIO = 1;
            VIDEO = 2;
        }
    }
    message ButtonsMessage {
         string contentText = 6;
         string footerText = 7;
         ContextInfo contextInfo = 8;
        repeated Button buttons = 9;
         HeaderType headerType = 10;
        oneof header {
            string text = 1;
            Message.DocumentMessage documentMessage = 2;
            Message.ImageMessage imageMessage = 3;
            Message.VideoMessage videoMessage = 4;
            Message.LocationMessage locationMessage = 5;
        }
        message Button {
             string buttonId = 1;
             ButtonText buttonText = 2;
             Type type = 3;
             NativeFlowInfo nativeFlowInfo = 4;
            message ButtonText {
                 string displayText = 1;
            }
            message NativeFlowInfo {
                 string name = 1;
                 string paramsJson = 2;
            }
            enum Type {
                UNKNOWN = 0;
                RESPONSE = 1;
                NATIVE_FLOW = 2;
            }
        }
        enum HeaderType {
            UNKNOWN = 0;
            EMPTY = 1;
            TEXT = 2;
            DOCUMENT = 3;
            IMAGE = 4;
            VIDEO = 5;
            LOCATION = 6;
        }
    }
    message ButtonsResponseMessage {
         string selectedButtonId = 1;
         ContextInfo contextInfo = 3;
         Type type = 4;
        oneof response {
            string selectedDisplayText = 2;
        }
        enum Type {
            UNKNOWN = 0;
            DISPLAY_TEXT = 1;
        }
    }
    message Call {
         bytes callKey = 1;
         string conversionSource = 2;
         bytes conversionData = 3;
         uint32 conversionDelaySeconds = 4;
         string ctwaSignals = 5;
         bytes ctwaPayload = 6;
         ContextInfo contextInfo = 7;
         string nativeFlowCallButtonPayload = 8;
         string deeplinkPayload = 9;
         MessageContextInfo messageContextInfo = 10;
    }
    message CallLogMessage {
         bool isVideo = 1;
         CallOutcome callOutcome = 2;
         int64 durationSecs = 3;
         CallType callType = 4;
        repeated CallParticipant participants = 5;
        enum CallOutcome {
            CONNECTED = 0;
            MISSED = 1;
            FAILED = 2;
            REJECTED = 3;
            ACCEPTED_ELSEWHERE = 4;
            ONGOING = 5;
            SILENCED_BY_DND = 6;
            SILENCED_UNKNOWN_CALLER = 7;
        }
        message CallParticipant {
             string jid = 1;
             Message.CallLogMessage.CallOutcome callOutcome = 2;
        }
        enum CallType {
            REGULAR = 0;
            SCHEDULED_CALL = 1;
            VOICE_CHAT = 2;
        }
    }
    message CancelPaymentRequestMessage {
         Protocol.MessageKey key = 1;
    }
    message Chat {
         string displayName = 1;
         string id = 2;
    }
    message CloudAPIThreadControlNotification {
         CloudAPIThreadControl status = 1;
         int64 senderNotificationTimestampMs = 2;
         string consumerLid = 3;
         string consumerPhoneNumber = 4;
         CloudAPIThreadControlNotificationContent notificationContent = 5;
         bool shouldSuppressNotification = 6;
        enum CloudAPIThreadControl {
            UNKNOWN = 0;
            CONTROL_PASSED = 1;
            CONTROL_TAKEN = 2;
        }
        message CloudAPIThreadControlNotificationContent {
             string handoffNotificationText = 1;
             string extraJson = 2;
        }
    }
    message CommentMessage {
         Message message = 1;
         Protocol.MessageKey targetMessageKey = 2;
    }
    message ContactMessage {
         string displayName = 1;
         string vcard = 16;
         ContextInfo contextInfo = 17;
    }
    message ContactsArrayMessage {
         string displayName = 1;
        repeated Message.ContactMessage contacts = 2;
         ContextInfo contextInfo = 17;
    }
    message DeclinePaymentRequestMessage {
         Protocol.MessageKey key = 1;
    }
    message DeviceSentMessage {
         string destinationJid = 1;
         Message message = 2;
         string phash = 3;
    }
    message DocumentMessage {
         string url = 1;
         string mimetype = 2;
         string title = 3;
         bytes fileSha256 = 4;
         uint64 fileLength = 5;
         uint32 pageCount = 6;
         bytes mediaKey = 7;
         string fileName = 8;
         bytes fileEncSha256 = 9;
         string directPath = 10;
         int64 mediaKeyTimestamp = 11;
         bool contactVcard = 12;
         string thumbnailDirectPath = 13;
         bytes thumbnailSha256 = 14;
         bytes thumbnailEncSha256 = 15;
         bytes jpegThumbnail = 16;
         ContextInfo contextInfo = 17;
         uint32 thumbnailHeight = 18;
         uint32 thumbnailWidth = 19;
         string caption = 20;
         string accessibilityLabel = 21;
         Message.MediaKeyDomain mediaKeyDomain = 22;
    }
    message EncCommentMessage {
         Protocol.MessageKey targetMessageKey = 1;
         bytes encPayload = 2;
         bytes encIv = 3;
    }
    message EncEventResponseMessage {
         Protocol.MessageKey eventCreationMessageKey = 1;
         bytes encPayload = 2;
         bytes encIv = 3;
    }
    message EncReactionMessage {
         Protocol.MessageKey targetMessageKey = 1;
         bytes encPayload = 2;
         bytes encIv = 3;
    }
    message EventMessage {
         ContextInfo contextInfo = 1;
         bool isCanceled = 2;
         string name = 3;
         string description = 4;
         Message.LocationMessage location = 5;
         string joinLink = 6;
         int64 startTime = 7;
         int64 endTime = 8;
         bool extraGuestsAllowed = 9;
         bool isScheduleCall = 10;
         bool hasReminder = 11;
         int64 reminderOffsetSec = 12;
    }
    message EventResponseMessage {
         EventResponseType response = 1;
         int64 timestampMs = 2;
         int32 extraGuestCount = 3;
        enum EventResponseType {
            UNKNOWN = 0;
            GOING = 1;
            NOT_GOING = 2;
            MAYBE = 3;
        }
    }
    message ExtendedTextMessage {
         string text = 1;
         string matchedText = 2;
         string description = 5;
         string title = 6;
         fixed32 textArgb = 7;
         fixed32 backgroundArgb = 8;
         FontType font = 9;
         PreviewType previewType = 10;
         bytes jpegThumbnail = 16;
         ContextInfo contextInfo = 17;
         bool doNotPlayInline = 18;
         string thumbnailDirectPath = 19;
         bytes thumbnailSha256 = 20;
         bytes thumbnailEncSha256 = 21;
         bytes mediaKey = 22;
         int64 mediaKeyTimestamp = 23;
         uint32 thumbnailHeight = 24;
         uint32 thumbnailWidth = 25;
         InviteLinkGroupType inviteLinkGroupType = 26;
         string inviteLinkParentGroupSubjectV2 = 27;
         bytes inviteLinkParentGroupThumbnailV2 = 28;
         InviteLinkGroupType inviteLinkGroupTypeV2 = 29;
         bool viewOnce = 30;
         uint32 videoHeight = 31;
         uint32 videoWidth = 32;
         Message.MMSThumbnailMetadata faviconMMSMetadata = 33;
         Message.LinkPreviewMetadata linkPreviewMetadata = 34;
         Message.PaymentLinkMetadata paymentLinkMetadata = 35;
        repeated Message.VideoEndCard endCardTiles = 36;
         string videoContentUrl = 37;
         EmbeddedMusic musicMetadata = 38;
         Message.PaymentExtendedMetadata paymentExtendedMetadata = 39;
        enum FontType {
            SYSTEM = 0;
            SYSTEM_TEXT = 1;
            FB_SCRIPT = 2;
            SYSTEM_BOLD = 6;
            MORNINGBREEZE_REGULAR = 7;
            CALISTOGA_REGULAR = 8;
            EXO2_EXTRABOLD = 9;
            COURIERPRIME_BOLD = 10;
        }
        enum InviteLinkGroupType {
            DEFAULT = 0;
            PARENT = 1;
            SUB = 2;
            DEFAULT_SUB = 3;
        }
        enum PreviewType {
            NONE = 0;
            VIDEO = 1;
            PLACEHOLDER = 4;
            IMAGE = 5;
            PAYMENT_LINKS = 6;
            PROFILE = 7;
        }
    }
    message FullHistorySyncOnDemandRequestMetadata {
         string requestId = 1;
    }
    message FutureProofMessage {
         Message message = 1;
    }
    message GroupInviteMessage {
         string groupJid = 1;
         string inviteCode = 2;
         int64 inviteExpiration = 3;
         string groupName = 4;
         bytes jpegThumbnail = 5;
         string caption = 6;
         ContextInfo contextInfo = 7;
         GroupType groupType = 8;
        enum GroupType {
            DEFAULT = 0;
            PARENT = 1;
        }
    }
    message HighlyStructuredMessage {
         string namespace = 1;
         string elementName = 2;
        repeated string params = 3;
         string fallbackLg = 4;
         string fallbackLc = 5;
        repeated HSMLocalizableParameter localizableParams = 6;
         string deterministicLg = 7;
         string deterministicLc = 8;
         Message.TemplateMessage hydratedHsm = 9;
        message HSMLocalizableParameter {
             string default = 1;
            oneof paramOneof {
                Message.HighlyStructuredMessage.HSMLocalizableParameter.HSMCurrency currency = 2;
                Message.HighlyStructuredMessage.HSMLocalizableParameter.HSMDateTime dateTime = 3;
            }
            message HSMCurrency {
                 string currencyCode = 1;
                 int64 amount1000 = 2;
            }
            message HSMDateTime {
                oneof datetimeOneof {
                    Message.HighlyStructuredMessage.HSMLocalizableParameter.HSMDateTime.HSMDateTimeComponent component = 1;
                    Message.HighlyStructuredMessage.HSMLocalizableParameter.HSMDateTime.HSMDateTimeUnixEpoch unixEpoch = 2;
                }
                message HSMDateTimeComponent {
                     DayOfWeekType dayOfWeek = 1;
                     uint32 year = 2;
                     uint32 month = 3;
                     uint32 dayOfMonth = 4;
                     uint32 hour = 5;
                     uint32 minute = 6;
                     CalendarType calendar = 7;
                    enum CalendarType {
                        GREGORIAN = 1;
                        SOLAR_HIJRI = 2;
                    }
                    enum DayOfWeekType {
                        MONDAY = 1;
                        TUESDAY = 2;
                        WEDNESDAY = 3;
                        THURSDAY = 4;
                        FRIDAY = 5;
                        SATURDAY = 6;
                        SUNDAY = 7;
                    }
                }
                message HSMDateTimeUnixEpoch {
                     int64 timestamp = 1;
                }
            }
        }
    }
    message HistorySyncMessageAccessStatus {
         bool completeAccessGranted = 1;
    }
    message HistorySyncNotification {
         bytes fileSha256 = 1;
         uint64 fileLength = 2;
         bytes mediaKey = 3;
         bytes fileEncSha256 = 4;
         string directPath = 5;
         Message.HistorySyncType syncType = 6;
         uint32 chunkOrder = 7;
         string originalMessageId = 8;
         uint32 progress = 9;
         int64 oldestMsgInChunkTimestampSec = 10;
         bytes initialHistBootstrapInlinePayload = 11;
         string peerDataRequestSessionId = 12;
         Message.FullHistorySyncOnDemandRequestMetadata fullHistorySyncOnDemandRequestMetadata = 13;
         string encHandle = 14;
         Message.HistorySyncMessageAccessStatus messageAccessStatus = 15;
    }
    enum HistorySyncType {
        INITIAL_BOOTSTRAP = 0;
        INITIAL_STATUS_V3 = 1;
        FULL = 2;
        RECENT = 3;
        PUSH_NAME = 4;
        NON_BLOCKING_DATA = 5;
        ON_DEMAND = 6;
        NO_HISTORY = 7;
        MESSAGE_ACCESS_STATUS = 8;
    }
    message ImageMessage {
         string url = 1;
         string mimetype = 2;
         string caption = 3;
         bytes fileSha256 = 4;
         uint64 fileLength = 5;
         uint32 height = 6;
         uint32 width = 7;
         bytes mediaKey = 8;
         bytes fileEncSha256 = 9;
        repeated InteractiveAnnotation interactiveAnnotations = 10;
         string directPath = 11;
         int64 mediaKeyTimestamp = 12;
         bytes jpegThumbnail = 16;
         ContextInfo contextInfo = 17;
         bytes firstScanSidecar = 18;
         uint32 firstScanLength = 19;
         uint32 experimentGroupId = 20;
         bytes scansSidecar = 21;
        repeated uint32 scanLengths = 22;
         bytes midQualityFileSha256 = 23;
         bytes midQualityFileEncSha256 = 24;
         bool viewOnce = 25;
         string thumbnailDirectPath = 26;
         bytes thumbnailSha256 = 27;
         bytes thumbnailEncSha256 = 28;
         string staticUrl = 29;
        repeated InteractiveAnnotation annotations = 30;
         ImageSourceType imageSourceType = 31;
         string accessibilityLabel = 32;
         Message.MediaKeyDomain mediaKeyDomain = 33;
         string qrUrl = 34;
        enum ImageSourceType {
            USER_IMAGE = 0;
            AI_GENERATED = 1;
            AI_MODIFIED = 2;
            RASTERIZED_TEXT_STATUS = 3;
        }
    }
    message InitialSecurityNotificationSettingSync {
         bool securityNotificationEnabled = 1;
    }
    message InteractiveMessage {
         Header header = 1;
         Body body = 2;
         Footer footer = 3;
         ContextInfo contextInfo = 15;
         UrlTrackingMap urlTrackingMap = 16;
        oneof interactiveMessage {
            Message.InteractiveMessage.ShopMessage shopStorefrontMessage = 4;
            Message.InteractiveMessage.CollectionMessage collectionMessage = 5;
            Message.InteractiveMessage.NativeFlowMessage nativeFlowMessage = 6;
            Message.InteractiveMessage.CarouselMessage carouselMessage = 7;
        }
        message Body {
             string text = 1;
        }
        message CarouselMessage {
            repeated Message.InteractiveMessage cards = 1;
             int32 messageVersion = 2;
             CarouselCardType carouselCardType = 3;
            enum CarouselCardType {
                UNKNOWN = 0;
                HSCROLL_CARDS = 1;
                ALBUM_IMAGE = 2;
            }
        }
        message CollectionMessage {
             string bizJid = 1;
             string id = 2;
             int32 messageVersion = 3;
        }
        message Footer {
             string text = 1;
             bool hasMediaAttachment = 3;
            oneof media {
                Message.AudioMessage audioMessage = 2;
            }
        }
        message Header {
             string title = 1;
             string subtitle = 2;
             bool hasMediaAttachment = 5;
            oneof media {
                Message.DocumentMessage documentMessage = 3;
                Message.ImageMessage imageMessage = 4;
                bytes jpegThumbnail = 6;
                Message.VideoMessage videoMessage = 7;
                Message.LocationMessage locationMessage = 8;
                Message.ProductMessage productMessage = 9;
            }
        }
        message NativeFlowMessage {
            repeated NativeFlowButton buttons = 1;
             string messageParamsJson = 2;
             int32 messageVersion = 3;
            message NativeFlowButton {
                 string name = 1;
                 string buttonParamsJson = 2;
            }
        }
        message ShopMessage {
             string id = 1;
             Surface surface = 2;
             int32 messageVersion = 3;
            enum Surface {
                UNKNOWN_SURFACE = 0;
                FB = 1;
                IG = 2;
                WA = 3;
            }
        }
    }
    message InteractiveResponseMessage {
         Body body = 1;
         ContextInfo contextInfo = 15;
        oneof interactiveResponseMessage {
            Message.InteractiveResponseMessage.NativeFlowResponseMessage nativeFlowResponseMessage = 2;
        }
        message Body {
             string text = 1;
             Format format = 2;
            enum Format {
                DEFAULT = 0;
                EXTENSIONS_1 = 1;
            }
        }
        message NativeFlowResponseMessage {
             string name = 1;
             string paramsJson = 2;
             int32 version = 3;
        }
    }
    message InvoiceMessage {
         string note = 1;
         string token = 2;
         AttachmentType attachmentType = 3;
         string attachmentMimetype = 4;
         bytes attachmentMediaKey = 5;
         int64 attachmentMediaKeyTimestamp = 6;
         bytes attachmentFileSha256 = 7;
         bytes attachmentFileEncSha256 = 8;
         string attachmentDirectPath = 9;
         bytes attachmentJpegThumbnail = 10;
        enum AttachmentType {
            IMAGE = 0;
            PDF = 1;
        }
    }
    message KeepInChatMessage {
         Protocol.MessageKey key = 1;
         KeepType keepType = 2;
         int64 timestampMs = 3;
    }
    message LinkPreviewMetadata {
         Message.PaymentLinkMetadata paymentLinkMetadata = 1;
         Message.URLMetadata urlMetadata = 2;
         uint32 fbExperimentId = 3;
         uint32 linkMediaDuration = 4;
         SocialMediaPostType socialMediaPostType = 5;
         bool linkInlineVideoMuted = 6;
         string videoContentUrl = 7;
         EmbeddedMusic musicMetadata = 8;
         string videoContentCaption = 9;
        enum SocialMediaPostType {
            NONE = 0;
            REEL = 1;
            LIVE_VIDEO = 2;
            LONG_VIDEO = 3;
            SINGLE_IMAGE = 4;
            CAROUSEL = 5;
        }
    }
    message ListMessage {
         string title = 1;
         string description = 2;
         string buttonText = 3;
         ListType listType = 4;
        repeated Section sections = 5;
         ProductListInfo productListInfo = 6;
         string footerText = 7;
         ContextInfo contextInfo = 8;
        enum ListType {
            UNKNOWN = 0;
            SINGLE_SELECT = 1;
            PRODUCT_LIST = 2;
        }
        message Product {
             string productId = 1;
        }
        message ProductListHeaderImage {
             string productId = 1;
             bytes jpegThumbnail = 2;
        }
        message ProductListInfo {
            repeated Message.ListMessage.ProductSection productSections = 1;
             Message.ListMessage.ProductListHeaderImage headerImage = 2;
             string businessOwnerJid = 3;
        }
        message ProductSection {
             string title = 1;
            repeated Message.ListMessage.Product products = 2;
        }
        message Row {
             string title = 1;
             string description = 2;
             string rowId = 3;
        }
        message Section {
             string title = 1;
            repeated Message.ListMessage.Row rows = 2;
        }
    }
    message ListResponseMessage {
         string title = 1;
         ListType listType = 2;
         SingleSelectReply singleSelectReply = 3;
         ContextInfo contextInfo = 4;
         string description = 5;
        enum ListType {
            UNKNOWN = 0;
            SINGLE_SELECT = 1;
        }
        message SingleSelectReply {
             string selectedRowId = 1;
        }
    }
    message LiveLocationMessage {
         double degreesLatitude = 1;
         double degreesLongitude = 2;
         uint32 accuracyInMeters = 3;
         float speedInMps = 4;
         uint32 degreesClockwiseFromMagneticNorth = 5;
         string caption = 6;
         int64 sequenceNumber = 7;
         uint32 timeOffset = 8;
         bytes jpegThumbnail = 16;
         ContextInfo contextInfo = 17;
    }
    message LocationMessage {
         double degreesLatitude = 1;
         double degreesLongitude = 2;
         string name = 3;
         string address = 4;
         string url = 5;
         bool isLive = 6;
         uint32 accuracyInMeters = 7;
         float speedInMps = 8;
         uint32 degreesClockwiseFromMagneticNorth = 9;
         string comment = 11;
         bytes jpegThumbnail = 16;
         ContextInfo contextInfo = 17;
    }
    message MMSThumbnailMetadata {
         string thumbnailDirectPath = 1;
         bytes thumbnailSha256 = 2;
         bytes thumbnailEncSha256 = 3;
         bytes mediaKey = 4;
         int64 mediaKeyTimestamp = 5;
         uint32 thumbnailHeight = 6;
         uint32 thumbnailWidth = 7;
         Message.MediaKeyDomain mediaKeyDomain = 8;
    }
    enum MediaKeyDomain {
        UNSET = 0;
        E2EE_CHAT = 1;
        STATUS = 2;
        CAPI = 3;
        BOT = 4;
    }
    message MessageHistoryBundle {
         string mimetype = 1;
         bytes fileSha256 = 2;
         bytes mediaKey = 3;
         bytes fileEncSha256 = 4;
         string directPath = 5;
         int64 mediaKeyTimestamp = 6;
         ContextInfo contextInfo = 7;
         Message.MessageHistoryMetadata messageHistoryMetadata = 8;
    }
    message MessageHistoryMetadata {
        repeated string historyReceivers = 1;
         int64 oldestMessageTimestamp = 2;
         int64 messageCount = 3;
    }
    message MessageHistoryNotice {
         ContextInfo contextInfo = 1;
         Message.MessageHistoryMetadata messageHistoryMetadata = 2;
    }
    message NewsletterAdminInviteMessage {
         string newsletterJid = 1;
         string newsletterName = 2;
         bytes jpegThumbnail = 3;
         string caption = 4;
         int64 inviteExpiration = 5;
         ContextInfo contextInfo = 6;
    }
    message NewsletterFollowerInviteMessage {
         string newsletterJid = 1;
         string newsletterName = 2;
         bytes jpegThumbnail = 3;
         string caption = 4;
         ContextInfo contextInfo = 5;
    }
    message OrderMessage {
         string orderId = 1;
         bytes thumbnail = 2;
         int32 itemCount = 3;
         OrderStatus status = 4;
         OrderSurface surface = 5;
         string message = 6;
         string orderTitle = 7;
         string sellerJid = 8;
         string token = 9;
         int64 totalAmount1000 = 10;
         string totalCurrencyCode = 11;
         ContextInfo contextInfo = 17;
         int32 messageVersion = 12;
         Protocol.MessageKey orderRequestMessageId = 13;
         string catalogType = 15;
        enum OrderStatus {
            INQUIRY = 1;
            ACCEPTED = 2;
            DECLINED = 3;
        }
        enum OrderSurface {
            CATALOG = 1;
        }
    }
    message PaymentExtendedMetadata {
         uint32 type = 1;
         string platform = 2;
    }
    message PaymentInviteMessage {
         ServiceType serviceType = 1;
         int64 expiryTimestamp = 2;
        enum ServiceType {
            UNKNOWN = 0;
            FBPAY = 1;
            NOVI = 2;
            UPI = 3;
        }
    }
    message PaymentLinkMetadata {
         PaymentLinkButton button = 1;
         PaymentLinkHeader header = 2;
         PaymentLinkProvider provider = 3;
        message PaymentLinkButton {
             string displayText = 1;
        }
        message PaymentLinkHeader {
             PaymentLinkHeaderType headerType = 1;
            enum PaymentLinkHeaderType {
                LINK_PREVIEW = 0;
                ORDER = 1;
            }
        }
        message PaymentLinkProvider {
             string paramsJson = 1;
        }
    }
    message PeerDataOperationRequestMessage {
         Message.PeerDataOperationRequestType peerDataOperationRequestType = 1;
        repeated RequestStickerReupload requestStickerReupload = 2;
        repeated RequestUrlPreview requestUrlPreview = 3;
         HistorySyncOnDemandRequest historySyncOnDemandRequest = 4;
        repeated PlaceholderMessageResendRequest placeholderMessageResendRequest = 5;
         FullHistorySyncOnDemandRequest fullHistorySyncOnDemandRequest = 6;
         SyncDCollectionFatalRecoveryRequest syncdCollectionFatalRecoveryRequest = 7;
         HistorySyncChunkRetryRequest historySyncChunkRetryRequest = 8;
         GalaxyFlowAction galaxyFlowAction = 9;
        message FullHistorySyncOnDemandRequest {
             Message.FullHistorySyncOnDemandRequestMetadata requestMetadata = 1;
             CompanionReg.DeviceProps.HistorySyncConfig historySyncConfig = 2;
        }
        message GalaxyFlowAction {
             GalaxyFlowActionType type = 1;
             string flowId = 2;
             string stanzaId = 3;
            enum GalaxyFlowActionType {
                NOTIFY_LAUNCH = 1;
            }
        }
        message HistorySyncChunkRetryRequest {
             Message.HistorySyncType syncType = 1;
             uint32 chunkOrder = 2;
             string chunkNotificationId = 3;
             bool regenerateChunk = 4;
        }
        message HistorySyncOnDemandRequest {
             string chatJid = 1;
             string oldestMsgId = 2;
             bool oldestMsgFromMe = 3;
             int32 onDemandMsgCount = 4;
             int64 oldestMsgTimestampMs = 5;
             string accountLid = 6;
        }
        message PlaceholderMessageResendRequest {
             Protocol.MessageKey messageKey = 1;
        }
        message RequestStickerReupload {
             string fileSha256 = 1;
        }
        message RequestUrlPreview {
             string url = 1;
             bool includeHqThumbnail = 2;
        }
        message SyncDCollectionFatalRecoveryRequest {
             string collectionName = 1;
             int64 timestamp = 2;
        }
    }
    message PeerDataOperationRequestResponseMessage {
         Message.PeerDataOperationRequestType peerDataOperationRequestType = 1;
         string stanzaId = 2;
        repeated PeerDataOperationResult peerDataOperationResult = 3;
        message PeerDataOperationResult {
             MmsRetry.MediaRetryNotification.ResultType mediaUploadResult = 1;
             Message.StickerMessage stickerMessage = 2;
             LinkPreviewResponse linkPreviewResponse = 3;
             PlaceholderMessageResendResponse placeholderMessageResendResponse = 4;
             WaffleNonceFetchResponse waffleNonceFetchRequestResponse = 5;
             FullHistorySyncOnDemandRequestResponse fullHistorySyncOnDemandRequestResponse = 6;
             CompanionMetaNonceFetchResponse companionMetaNonceFetchRequestResponse = 7;
             SyncDSnapshotFatalRecoveryResponse syncdSnapshotFatalRecoveryResponse = 8;
             CompanionCanonicalUserNonceFetchResponse companionCanonicalUserNonceFetchRequestResponse = 9;
             HistorySyncChunkRetryResponse historySyncChunkRetryResponse = 10;
            message CompanionCanonicalUserNonceFetchResponse {
                 string nonce = 1;
                 string waFbid = 2;
                 bool forceRefresh = 3;
            }
            message CompanionMetaNonceFetchResponse {
                 string nonce = 1;
            }
            message FullHistorySyncOnDemandRequestResponse {
                 Message.FullHistorySyncOnDemandRequestMetadata requestMetadata = 1;
                 Message.PeerDataOperationRequestResponseMessage.PeerDataOperationResult.FullHistorySyncOnDemandResponseCode responseCode = 2;
            }
            enum FullHistorySyncOnDemandResponseCode {
                REQUEST_SUCCESS = 0;
                REQUEST_TIME_EXPIRED = 1;
                DECLINED_SHARING_HISTORY = 2;
                GENERIC_ERROR = 3;
                ERROR_REQUEST_ON_NON_SMB_PRIMARY = 4;
                ERROR_HOSTED_DEVICE_NOT_CONNECTED = 5;
                ERROR_HOSTED_DEVICE_LOGIN_TIME_NOT_SET = 6;
            }
            message HistorySyncChunkRetryResponse {
                 Message.HistorySyncType syncType = 1;
                 uint32 chunkOrder = 2;
                 string requestId = 3;
                 Message.PeerDataOperationRequestResponseMessage.PeerDataOperationResult.HistorySyncChunkRetryResponseCode responseCode = 4;
                 bool canRecover = 5;
            }
            enum HistorySyncChunkRetryResponseCode {
                GENERATION_ERROR = 1;
                CHUNK_CONSUMED = 2;
                TIMEOUT = 3;
                SESSION_EXHAUSTED = 4;
                CHUNK_EXHAUSTED = 5;
                DUPLICATED_REQUEST = 6;
            }
            message LinkPreviewResponse {
                 string url = 1;
                 string title = 2;
                 string description = 3;
                 bytes thumbData = 4;
                 string matchText = 6;
                 string previewType = 7;
                 LinkPreviewHighQualityThumbnail hqThumbnail = 8;
                 PaymentLinkPreviewMetadata previewMetadata = 9;
                message LinkPreviewHighQualityThumbnail {
                     string directPath = 1;
                     string thumbHash = 2;
                     string encThumbHash = 3;
                     bytes mediaKey = 4;
                     int64 mediaKeyTimestampMs = 5;
                     int32 thumbWidth = 6;
                     int32 thumbHeight = 7;
                }
                message PaymentLinkPreviewMetadata {
                     bool isBusinessVerified = 1;
                     string providerName = 2;
                }
            }
            message PlaceholderMessageResendResponse {
                 bytes webMessageInfoBytes = 1;
            }
            message SyncDSnapshotFatalRecoveryResponse {
                 bytes collectionSnapshot = 1;
                 bool isCompressed = 2;
            }
            message WaffleNonceFetchResponse {
                 string nonce = 1;
                 string waEntFbid = 2;
            }
        }
    }
    enum PeerDataOperationRequestType {
        UPLOAD_STICKER = 0;
        SEND_RECENT_STICKER_BOOTSTRAP = 1;
        GENERATE_LINK_PREVIEW = 2;
        HISTORY_SYNC_ON_DEMAND = 3;
        PLACEHOLDER_MESSAGE_RESEND = 4;
        WAFFLE_LINKING_NONCE_FETCH = 5;
        FULL_HISTORY_SYNC_ON_DEMAND = 6;
        COMPANION_META_NONCE_FETCH = 7;
        COMPANION_SYNCD_SNAPSHOT_FATAL_RECOVERY = 8;
        COMPANION_CANONICAL_USER_NONCE_FETCH = 9;
        HISTORY_SYNC_CHUNK_RETRY = 10;
        GALAXY_FLOW_ACTION = 11;
    }
    message PinInChatMessage {
         Protocol.MessageKey key = 1;
         Type type = 2;
         int64 senderTimestampMs = 3;
        enum Type {
            UNKNOWN_TYPE = 0;
            PIN_FOR_ALL = 1;
            UNPIN_FOR_ALL = 2;
        }
    }
    message PlaceholderMessage {
         PlaceholderType type = 1;
        enum PlaceholderType {
            MASK_LINKED_DEVICES = 0;
        }
    }
    enum PollContentType {
        UNKNOWN = 0;
        TEXT = 1;
        IMAGE = 2;
    }
    message PollCreationMessage {
         bytes encKey = 1;
         string name = 2;
        repeated Option options = 3;
         uint32 selectableOptionsCount = 4;
         ContextInfo contextInfo = 5;
         Message.PollContentType pollContentType = 6;
         Message.PollType pollType = 7;
         Option correctAnswer = 8;
        message Option {
             string optionName = 1;
             string optionHash = 2;
        }
    }
    message PollEncValue {
         bytes encPayload = 1;
         bytes encIv = 2;
    }
    message PollResultSnapshotMessage {
         string name = 1;
        repeated PollVote pollVotes = 2;
         ContextInfo contextInfo = 3;
         Message.PollType pollType = 4;
        message PollVote {
             string optionName = 1;
             int64 optionVoteCount = 2;
        }
    }
    enum PollType {
        POLL = 0;
        QUIZ = 1;
    }
    message PollUpdateMessage {
         Protocol.MessageKey pollCreationMessageKey = 1;
         Message.PollEncValue vote = 2;
         Message.PollUpdateMessageMetadata metadata = 3;
         int64 senderTimestampMs = 4;
    }
    message PollUpdateMessageMetadata {
    }
    message PollVoteMessage {
        repeated bytes selectedOptions = 1;
    }
    message ProductMessage {
         ProductSnapshot product = 1;
         string businessOwnerJid = 2;
         CatalogSnapshot catalog = 4;
         string body = 5;
         string footer = 6;
         ContextInfo contextInfo = 17;
        message CatalogSnapshot {
             Message.ImageMessage catalogImage = 1;
             string title = 2;
             string description = 3;
        }
        message ProductSnapshot {
             Message.ImageMessage productImage = 1;
             string productId = 2;
             string title = 3;
             string description = 4;
             string currencyCode = 5;
             int64 priceAmount1000 = 6;
             string retailerId = 7;
             string url = 8;
             uint32 productImageCount = 9;
             string firstImageId = 11;
             int64 salePriceAmount1000 = 12;
             string signedUrl = 13;
        }
    }
    message ProtocolMessage {
         Protocol.MessageKey key = 1;
         Type type = 2;
         uint32 ephemeralExpiration = 4;
         int64 ephemeralSettingTimestamp = 5;
         Message.HistorySyncNotification historySyncNotification = 6;
         Message.AppStateSyncKeyShare appStateSyncKeyShare = 7;
         Message.AppStateSyncKeyRequest appStateSyncKeyRequest = 8;
         Message.InitialSecurityNotificationSettingSync initialSecurityNotificationSettingSync = 9;
         Message.AppStateFatalExceptionNotification appStateFatalExceptionNotification = 10;
         DisappearingMode disappearingMode = 11;
         Message editedMessage = 14;
         int64 timestampMs = 15;
         Message.PeerDataOperationRequestMessage peerDataOperationRequestMessage = 16;
         Message.PeerDataOperationRequestResponseMessage peerDataOperationRequestResponseMessage = 17;
         AICommon.BotFeedbackMessage botFeedbackMessage = 18;
         string invokerJid = 19;
         Message.RequestWelcomeMessageMetadata requestWelcomeMessageMetadata = 20;
         MediaNotifyMessage mediaNotifyMessage = 21;
         Message.CloudAPIThreadControlNotification cloudApiThreadControlNotification = 22;
         LIDMigrationMappingSyncMessage lidMigrationMappingSyncMessage = 23;
         Protocol.LimitSharing limitSharing = 24;
         bytes aiPsiMetadata = 25;
         AIQueryFanout aiQueryFanout = 26;
         MemberLabel memberLabel = 27;
        enum Type {
            REVOKE = 0;
            EPHEMERAL_SETTING = 3;
            EPHEMERAL_SYNC_RESPONSE = 4;
            HISTORY_SYNC_NOTIFICATION = 5;
            APP_STATE_SYNC_KEY_SHARE = 6;
            APP_STATE_SYNC_KEY_REQUEST = 7;
            MSG_FANOUT_BACKFILL_REQUEST = 8;
            INITIAL_SECURITY_NOTIFICATION_SETTING_SYNC = 9;
            APP_STATE_FATAL_EXCEPTION_NOTIFICATION = 10;
            SHARE_PHONE_NUMBER = 11;
            MESSAGE_EDIT = 14;
            PEER_DATA_OPERATION_REQUEST_MESSAGE = 16;
            PEER_DATA_OPERATION_REQUEST_RESPONSE_MESSAGE = 17;
            REQUEST_WELCOME_MESSAGE = 18;
            BOT_FEEDBACK_MESSAGE = 19;
            MEDIA_NOTIFY_MESSAGE = 20;
            CLOUD_API_THREAD_CONTROL_NOTIFICATION = 21;
            LID_MIGRATION_MAPPING_SYNC = 22;
            REMINDER_MESSAGE = 23;
            BOT_MEMU_ONBOARDING_MESSAGE = 24;
            STATUS_MENTION_MESSAGE = 25;
            STOP_GENERATION_MESSAGE = 26;
            LIMIT_SHARING = 27;
            AI_PSI_METADATA = 28;
            AI_QUERY_FANOUT = 29;
            GROUP_MEMBER_LABEL_CHANGE = 30;
        }
    }
    message QuestionResponseMessage {
         Protocol.MessageKey key = 1;
         string text = 2;
    }
    message ReactionMessage {
         Protocol.MessageKey key = 1;
         string text = 2;
         string groupingKey = 3;
         int64 senderTimestampMs = 4;
    }
    message RequestPaymentMessage {
         Message noteMessage = 4;
         string currencyCodeIso4217 = 1;
         uint64 amount1000 = 2;
         string requestFrom = 3;
         int64 expiryTimestamp = 5;
         Money amount = 6;
         PaymentBackground background = 7;
    }
    message RequestPhoneNumberMessage {
         ContextInfo contextInfo = 1;
    }
    message RequestWelcomeMessageMetadata {
         LocalChatState localChatState = 1;
        enum LocalChatState {
            EMPTY = 0;
            NON_EMPTY = 1;
        }
    }
    message ScheduledCallCreationMessage {
         int64 scheduledTimestampMs = 1;
         CallType callType = 2;
         string title = 3;
        enum CallType {
            UNKNOWN = 0;
            VOICE = 1;
            VIDEO = 2;
        }
    }
    message ScheduledCallEditMessage {
         Protocol.MessageKey key = 1;
         EditType editType = 2;
        enum EditType {
            UNKNOWN = 0;
            CANCEL = 1;
        }
    }
    message SecretEncryptedMessage {
         Protocol.MessageKey targetMessageKey = 1;
         bytes encPayload = 2;
         bytes encIv = 3;
         SecretEncType secretEncType = 4;
        enum SecretEncType {
            UNKNOWN = 0;
            EVENT_EDIT = 1;
            MESSAGE_EDIT = 2;
        }
    }
    message SendPaymentMessage {
         Message noteMessage = 2;
         Protocol.MessageKey requestMessageKey = 3;
         PaymentBackground background = 4;
         string transactionData = 5;
    }
    message SenderKeyDistributionMessage {
         string groupId = 1;
         bytes axolotlSenderKeyDistributionMessage = 2;
    }
    message StatusNotificationMessage {
         Protocol.MessageKey responseMessageKey = 1;
         Protocol.MessageKey originalMessageKey = 2;
         StatusNotificationType type = 3;
        enum StatusNotificationType {
            UNKNOWN = 0;
            STATUS_ADD_YOURS = 1;
            STATUS_RESHARE = 2;
            STATUS_QUESTION_ANSWER_RESHARE = 3;
        }
    }
    message StatusQuestionAnswerMessage {
         Protocol.MessageKey key = 1;
         string text = 2;
    }
    message StatusQuotedMessage {
         StatusQuotedMessageType type = 1;
         string text = 2;
         bytes thumbnail = 3;
         Protocol.MessageKey originalStatusId = 4;
        enum StatusQuotedMessageType {
            QUESTION_ANSWER = 1;
        }
    }
    message StatusStickerInteractionMessage {
         Protocol.MessageKey key = 1;
         string stickerKey = 2;
         StatusStickerType type = 3;
        enum StatusStickerType {
            UNKNOWN = 0;
            REACTION = 1;
        }
    }
    message StickerMessage {
         string url = 1;
         bytes fileSha256 = 2;
         bytes fileEncSha256 = 3;
         bytes mediaKey = 4;
         string mimetype = 5;
         uint32 height = 6;
         uint32 width = 7;
         string directPath = 8;
         uint64 fileLength = 9;
         int64 mediaKeyTimestamp = 10;
         uint32 firstFrameLength = 11;
         bytes firstFrameSidecar = 12;
         bool isAnimated = 13;
         bytes pngThumbnail = 16;
         ContextInfo contextInfo = 17;
         int64 stickerSentTs = 18;
         bool isAvatar = 19;
         bool isAiSticker = 20;
         bool isLottie = 21;
         string accessibilityLabel = 22;
         Message.MediaKeyDomain mediaKeyDomain = 23;
    }
    message StickerPackMessage {
         string stickerPackId = 1;
         string name = 2;
         string publisher = 3;
        repeated Sticker stickers = 4;
         uint64 fileLength = 5;
         bytes fileSha256 = 6;
         bytes fileEncSha256 = 7;
         bytes mediaKey = 8;
         string directPath = 9;
         string caption = 10;
         ContextInfo contextInfo = 11;
         string packDescription = 12;
         int64 mediaKeyTimestamp = 13;
         string trayIconFileName = 14;
         string thumbnailDirectPath = 15;
         bytes thumbnailSha256 = 16;
         bytes thumbnailEncSha256 = 17;
         uint32 thumbnailHeight = 18;
         uint32 thumbnailWidth = 19;
         string imageDataHash = 20;
         uint64 stickerPackSize = 21;
         StickerPackOrigin stickerPackOrigin = 22;
        message Sticker {
             string fileName = 1;
             bool isAnimated = 2;
            repeated string emojis = 3;
             string accessibilityLabel = 4;
             bool isLottie = 5;
             string mimetype = 6;
        }
        enum StickerPackOrigin {
            FIRST_PARTY = 0;
            THIRD_PARTY = 1;
            USER_CREATED = 2;
        }
    }
    message StickerSyncRMRMessage {
        repeated string filehash = 1;
         string rmrSource = 2;
         int64 requestTimestamp = 3;
    }
    message TemplateButtonReplyMessage {
         string selectedId = 1;
         string selectedDisplayText = 2;
         ContextInfo contextInfo = 3;
         uint32 selectedIndex = 4;
         uint32 selectedCarouselCardIndex = 5;
    }
    message TemplateMessage {
         ContextInfo contextInfo = 3;
         HydratedFourRowTemplate hydratedTemplate = 4;
         string templateId = 9;
        oneof format {
            Message.TemplateMessage.FourRowTemplate fourRowTemplate = 1;
            Message.TemplateMessage.HydratedFourRowTemplate hydratedFourRowTemplate = 2;
            Message.InteractiveMessage interactiveMessageTemplate = 5;
        }
        message FourRowTemplate {
             Message.HighlyStructuredMessage content = 6;
             Message.HighlyStructuredMessage footer = 7;
            repeated TemplateButton buttons = 8;
            oneof title {
                Message.DocumentMessage documentMessage = 1;
                Message.HighlyStructuredMessage highlyStructuredMessage = 2;
                Message.ImageMessage imageMessage = 3;
                Message.VideoMessage videoMessage = 4;
                Message.LocationMessage locationMessage = 5;
            }
        }
        message HydratedFourRowTemplate {
             string hydratedContentText = 6;
             string hydratedFooterText = 7;
            repeated HydratedTemplateButton hydratedButtons = 8;
             string templateId = 9;
             bool maskLinkedDevices = 10;
            oneof title {
                Message.DocumentMessage documentMessage = 1;
                string hydratedTitleText = 2;
                Message.ImageMessage imageMessage = 3;
                Message.VideoMessage videoMessage = 4;
                Message.LocationMessage locationMessage = 5;
            }
        }
    }
    message URLMetadata {
         uint32 fbExperimentId = 1;
    }
    message VideoEndCard {
         string username = 1;
         string caption = 2;
         string thumbnailImageUrl = 3;
         string profilePictureUrl = 4;
    }
    message VideoMessage {
         string url = 1;
         string mimetype = 2;
         bytes fileSha256 = 3;
         uint64 fileLength = 4;
         uint32 seconds = 5;
         bytes mediaKey = 6;
         string caption = 7;
         bool gifPlayback = 8;
         uint32 height = 9;
         uint32 width = 10;
         bytes fileEncSha256 = 11;
        repeated InteractiveAnnotation interactiveAnnotations = 12;
         string directPath = 13;
         int64 mediaKeyTimestamp = 14;
         bytes jpegThumbnail = 16;
         ContextInfo contextInfo = 17;
         bytes streamingSidecar = 18;
         Attribution gifAttribution = 19;
         bool viewOnce = 20;
         string thumbnailDirectPath = 21;
         bytes thumbnailSha256 = 22;
         bytes thumbnailEncSha256 = 23;
         string staticUrl = 24;
        repeated InteractiveAnnotation annotations = 25;
         string accessibilityLabel = 26;
        repeated ProcessedVideo processedVideos = 27;
         uint32 externalShareFullVideoDurationInSeconds = 28;
         uint64 motionPhotoPresentationOffsetMs = 29;
         string metadataUrl = 30;
         VideoSourceType videoSourceType = 31;
         Message.MediaKeyDomain mediaKeyDomain = 32;
        enum Attribution {
            NONE = 0;
            GIPHY = 1;
            TENOR = 2;
            KLIPY = 3;
        }
        enum VideoSourceType {
            USER_VIDEO = 0;
            AI_GENERATED = 1;
        }
    }
}

enum KeepType {
    UNKNOWN = 0;
    KEEP_FOR_ALL = 1;
    UNDO_KEEP_FOR_ALL = 2;
}

enum WebLinkRenderConfig {
    WEBVIEW = 0;
    SYSTEM = 1;
}